/* Datos del estudio · 36 resorts todo incluido · 29 dic 2026 – 2 ene 2027
   r = [categoría, m², ocupación, incluye, USD/noche, total 4 noches USD]
   img = [urlHabitación, urlAlberca, urlPlaya]  (verificadas contra el CDN oficial)
   Precios: [OF] tarifa oficial "desde" · [EST] estimación con recargo festivo. Verificar antes de pagar. */
const FX = 17.35;

const HOTELS = [
/* ===================== PUNTA CANA · SOLO ADULTOS ===================== */
{
 id:"majestic-colonial", dest:"pc", tipo:"adultos", nombre:"Majestic Colonial · Colonial Club",
 cadena:"Majestic Resorts", zona:"Arena Gorda, Bávaro", ta:"4.5", taN:"26,388", taRank:"#2 de 56 en Bávaro",
 badge:"Reabre nov 2026", badgeCls:"warn",
 web:"https://www.majestic-resorts.com/punta-cana/resorts/majestic-colonial-punta-cana",
 rooms:"https://www.majestic-resorts.com/punta-cana/resorts/majestic-colonial-punta-cana/rooms",
 gal:"https://www.majestic-resorts.com/punta-cana/resorts/majestic-colonial-punta-cana/gallery",
 datos:"318 suites en el Club · reapertura 12 nov 2026 tras renovación de USD 35 M · swim-up bar sí (2 exclusivos del Club)",
 alerta:"Cerrado por renovación integral; reabre el 12 de noviembre de 2026, apenas 7 semanas antes del viaje. Producto nuevo, pero con riesgo de rodaje.",
 img:["https://www.majestic-resorts.com/dam/jcr:8abf4c24-c96f-40e1-9e6c-bb5069d3b8cf/gallery10-majestic-colonial-punta-cana.jpg",
      "https://www.majestic-resorts.com/dam/jcr:f046c838-307b-4074-b9cc-8b37e34a12eb/gallery16-majestic-colonial-punta-cana.jpg",
      "https://www.majestic-resorts.com/dam/jcr:9eb126aa-5721-420e-919b-70cc8cf664fc/gallery12-majestic-colonial-punta-cana.jpg"],
 r:[["Colonial Club Jr. Suite (jacuzzi ext.)","49","4 ad.","Balcón, jacuzzi interior y exterior, mayordomo, room service 24 h","660 EST","2,640"],
    ["Colonial Club Jr. Suite Ocean View","49","2 ad.","Vista mar, jacuzzi, Nespresso, mayordomo","740 EST","2,960"],
    ["Colonial Club Majestic Jr. Suite Swim Up","49","2 ad.","Acceso directo a alberca, jardín semiprivado","800 EST","3,200"],
    ["Colonial Club Jr. Suite Oceanfront","49","2 ad.","3er piso frente al mar, terraza con camastros","840 EST","3,360"],
    ["Colonial Club One Bedroom Suite","99","4 ad.","Sala separada, 4º piso, jacuzzi","1,040 EST","4,160"]]
},
{
 id:"secrets-royal-beach", dest:"pc", tipo:"adultos", nombre:"Secrets Royal Beach Punta Cana",
 cadena:"Hyatt Inclusive Collection", zona:"Bávaro · Los Corales", ta:"4.6", taN:"23,532", taRank:"#20 de 169 en Punta Cana",
 badge:"Mejor equilibrio", badgeCls:"best",
 web:"https://www.hyattinclusivecollection.com/en/resorts-hotels/secrets/dominican-republic/royal-beach-punta-cana/",
 rooms:"https://www.hyattinclusivecollection.com/en/resorts-hotels/secrets/dominican-republic/royal-beach-punta-cana/accommodations/rooms-suites/",
 gal:"https://www.hyattinclusivecollection.com/en/resorts-hotels/secrets/dominican-republic/royal-beach-punta-cana/gallery/",
 datos:"639 suites en 12 categorías · reconstruido en 2020 (USD 36 M) · swim-up bar sí · playa de 105 m de ancho",
 img:["https://alg.widen.net/content/okdyzavqks/webp/SERPC-JR-TV-TER-1A-CB.webp?u=itfpsm&download=true&q=80",
      "https://alg.widen.net/content/5jhdvtb2da/webp/SERPC-EXT-MainPool-3A-CB.webp?u=itfpsm&download=true&q=80",
      "https://alg.widen.net/content/mvxrjq4fck/webp/SERPC-EXT-Infinity-Pool-01-SB.webp?u=itfpsm&download=true&q=80"],
 r:[["Junior Suite","40","2-3","Balcón amueblado, baño de mármol","392 OF → 785 EST","3,140"],
    ["Junior Suite Tropical View","40","2-3","Vista tropical","412 OF → 825 EST","3,300"],
    ["Junior Suite Pool View","40","2-3","Vista alberca","431 OF → 862 EST","3,450"],
    ["Junior Suite Partial Ocean View","40","2-3","Vista parcial al mar","471 OF → 942 EST","3,770"],
    ["Junior Suite Private Pool","40","2-3","Alberca privada en terraza","529 OF → 1,058 EST","4,230"],
    ["Preferred Club Jr. Suite Tropical","54","2","Lounge, alberca y playa exclusivas","569 OF → 1,138 EST","4,550"],
    ["Preferred Club Jr. Suite Swim Up","54","2","Preferred + swim-up","627 OF → 1,254 EST","5,020"],
    ["PC Master Suite Ocean Front","118","2","Frente al mar, terraza con tina","823 OF → 1,646 EST","6,580"]]
},
{
 id:"trs-turquesa", dest:"pc", tipo:"adultos", nombre:"TRS Turquesa Hotel",
 cadena:"Palladium Hotel Group", zona:"Bávaro · El Cortecito", ta:"4.5", taN:"20,636", taRank:"#19 de 56 en Bávaro",
 badge:"El más céntrico", badgeCls:"ok",
 web:"https://www.palladiumhotelgroup.com/en/hotels/republicadominicana/puntacana/trs-turquesa-hotel",
 rooms:"https://www.palladiumhotelgroup.com/en/hotels/republicadominicana/puntacana/trs-turquesa-hotel/rooms",
 gal:"https://www.palladiumhotelgroup.com/en/hotels/republicadominicana/puntacana/trs-turquesa-hotel",
 datos:"369 suites · mayordomo incluido · acceso a 40+ restaurantes y bares del complejo Grand Palladium · walkability 87/100",
 img:["https://www.palladiumhotelgroup.com/content/dam/palladium/images/hoteles/republica-dominicana/punta-cana/habitaciones/trs-turquesa-hotel/junior-suite-swim-up/Royal-Deluxe-Junior-Suite-swim-up-1-.jpg",
      "https://www.palladiumhotelgroup.com/content/dam/palladium/images/hoteles/republica-dominicana/punta-cana/habitaciones/trs-turquesa-hotel/junior-suite-garden-pool-view/TRS-TURQUESA-JUNIOR-SUITE-GARDEN-POOL-VIEW-5535-DJI_0311.jpg",
      "https://www.palladiumhotelgroup.com/content/dam/palladium/images/hoteles/republica-dominicana/punta-cana/habitaciones/trs-turquesa-hotel/romance-suite-swim-up/TRS-TURQUESA-ROMANCE-SUITE-SWIM-UP-5506_MG_1925.jpg"],
 r:[["Junior Suite Garden/Pool View","44","3","Terraza, tina de hidromasaje, mayordomo","860 EST","3,440"],
    ["Junior Suite Poolside","44","3","Junto a alberca","900 EST","3,600"],
    ["Junior Suite Swim Up","44","3","Acceso swim-up, cama con dosel","1,020 EST","4,080"],
    ["Romance Suite Poolside","58","2","Jacuzzi de mármol privado, regadera de lluvia","1,100 EST","4,400"],
    ["Jacuzzi Terrace Suite Beachside","55","2","Junto a la playa, jacuzzi privado","1,220 EST","4,880"],
    ["Villa Suite Swim Up","68","2","Terraza con acceso swim-up","1,340 EST","5,360"],
    ["Ambassador Suite","90","2","Terraza con jacuzzi integrado y daybed","1,600 EST","6,400"]]
},
{
 id:"majestic-mirage", dest:"pc", tipo:"adultos", nombre:"Majestic Mirage · Mirage Club",
 cadena:"Majestic Resorts", zona:"Arena Gorda, Bávaro", ta:"4.7", taN:"16,719", taRank:"#7 de 170 en Punta Cana",
 badge:"Mejores albercas", badgeCls:"ok",
 web:"https://www.majestic-resorts.com/punta-cana/resorts/majestic-mirage-punta-cana-all-suite-resort",
 rooms:"https://www.majestic-resorts.com/punta-cana/resorts/majestic-mirage-punta-cana-all-suite-resort/suites",
 gal:"https://www.majestic-resorts.com/punta-cana/resorts/majestic-mirage-punta-cana-all-suite-resort/gallery",
 datos:"358 suites de 93 m² · abierto 2016 · 12 albercas, 8 privadas del Club · 4 swim-up bars, 3 exclusivos · acceso 18+ restringido",
 img:["https://www.majestic-resorts.com/dam/jcr:57936bbb-cddb-4aa7-9950-3266e01ec7f1/gallery1-majestic-mirage-punta-cana.jpg",
      "https://www.majestic-resorts.com/dam/jcr:242d8e7d-edae-4cdb-96eb-06b6748ef456/gallery3-majestic-mirage-punta-cana.jpg",
      "https://www.majestic-resorts.com/dam/jcr:37f2150e-24ee-430a-b83c-94e23b56cf3b/gallery17-majestic-mirage-punta-cana.jpg"],
 r:[["Mirage Club One Bedroom Suite","93","4 ad.","Sala y recámara separadas, tina exenta, medio baño, jacuzzi exterior","860 EST","3,440"],
    ["Mirage Club Ocean View Suite","93","4 ad.","Vista al mar, sala separada, jacuzzi exterior","960 EST","3,840"],
    ["Mirage Club Swim Up Suite","93","4 ad.","Acceso directo a alberca, cama balinesa en jardín","1,020 EST","4,080"],
    ["Mirage Club Sky View Suite","93 (2 niveles)","2 ad.","Rooftop privado con cama balinesa y jacuzzi","1,180 EST","4,720"]]
},
{
 id:"barcelo-bavaro-beach", dest:"pc", tipo:"adultos", nombre:"Barceló Bávaro Beach",
 cadena:"Barceló", zona:"Bávaro", ta:"4.4", taN:"16,448", taRank:"#23 de 56 en Bávaro",
 badge:"El más barato", badgeCls:"ok",
 web:"https://www.barcelo.com/en-us/barcelo-bavaro-beach/",
 rooms:"https://www.barcelo.com/en-us/barcelo-bavaro-beach/rooms/",
 gal:"https://www.barcelo.com/en-us/barcelo-bavaro-beach/galleries/",
 datos:"589 habitaciones · convertido a solo adultos ~2018 · swim-up bar sí · acceso al complejo Barceló Bávaro Grand Resort · playa 9/10",
 alerta:"La web oficial marcó “no disponible” para 29 dic 2026 – 2 ene 2027 al momento de la consulta. Verificar disponibilidad real.",
 img:["https://www.bavarobeachpuntacana.com/images/rooms/superior-room-ocean-view.jpg",
      "https://www.bavarobeachpuntacana.com/images/slides/slide-23.jpg",
      "https://www.bavarobeachpuntacana.com/images/rooms/superior-oceanfront-premium-level.jpg"],
 r:[["Superior Room","47","4 ad.","Balcón o terraza, wifi, albornoz","196-201 OF → 400 EST","1,600"],
    ["Superior Sea View Premium Level","47","4 ad.","Vista lateral al mar + lounge exclusivo","225-231 OF → 460 EST","1,840"],
    ["Superior Ocean Front Premium Level","47","4 ad.","Frente al mar + beneficios Premium","245-250 OF → 500 EST","2,000"],
    ["Superior Swim Up Premium Level","47","4 ad.","Swim-up + Premium Level","294-301 OF → 600 EST","2,400"],
    ["Premium Level Ocean Front Suite","94","2 ad.","Doble tamaño, frente al mar, hot tub","391-401 OF → 800 EST","3,200"]]
},
{
 id:"joia-bavaro", dest:"pc", tipo:"adultos", nombre:"JOIA Bávaro by Iberostar",
 cadena:"Iberostar", zona:"Arena Gorda, Bávaro", ta:"4.8", taN:"16,193", taRank:"#1 de 56 en Bávaro",
 badge:"Mejor comida", badgeCls:"ok",
 web:"https://www.iberostar.com/en/hotels/punta-cana/joia-bavaro-by-iberostar/",
 rooms:"https://www.ihg.com/joia-iberostar/hotels/us/en/punta-cana/ghbgb/hoteldetail/rooms",
 gal:"https://www.iberostar.com/en/hotels/punta-cana/joia-bavaro-by-iberostar/",
 datos:"273 suites · ex Iberostar Grand, rebautizado JOIA en 2024 · albercas climatizadas · golf 18 hoyos incluido · traslado gratis con 3+ noches directo",
 img:["https://www.iberostarbavarogrand.com/images/rooms/swim-out-butler-suite.jpg",
      "https://apiimg.iberostar.com/uploads/image/81279/crops/16:9/1920/image.jpeg",
      "https://www.iberostarbavarogrand.com/images/rooms/ocean-front-butler-suite.jpg"],
 r:[["Suite (vista jardín)","33","2","Balcón, tina de hidromasaje","507-572 OF → 1,000 EST","4,000"],
    ["Upper Floor Suite","33","2","Pisos altos, hamaca colgante, doble lavabo","1,030 EST","4,120"],
    ["Ocean View Butler Suite","33","2","Vista mar, jacuzzi, mayordomo","1,120 EST","4,480"],
    ["Swim Out Butler Suite","40","2","Alberca semiprivada desde la terraza, mayordomo","1,190 EST","4,760"],
    ["Ocean Front Butler Suite","53-55","2","Frente al mar, la más amplia, jacuzzi spa","1,330 EST","5,320"]]
},
{
 id:"paradisus-palma-real", dest:"pc", tipo:"adultos", nombre:"Paradisus Palma Real · The Reserve",
 cadena:"Meliá", zona:"Bávaro · Palma Real", ta:"4.5", taN:"26,487", taRank:"#8 de 56 en Bávaro",
 web:"https://www.melia.com/en/hotels/dominican-republic/punta-cana/paradisus-palma-real-golf-and-spa-resort",
 rooms:"https://www.melia.com/en/hotels/dominican-republic/punta-cana/paradisus-palma-real-golf-and-spa-resort/rooms",
 gal:"https://www.palmarealresort.com/accommodations.asp",
 datos:"Sección solo adultos dentro del complejo · renovación de USD 40 M (2023-24) · alberca, lounge, playa y restaurante Santé exclusivos · Palma Real Shopping Village enfrente",
 img:[],
 r:[["The Reserve Jr. Suite Garden View","48","2 ad.","Terraza, salón con sofá cama, concierge, check-in privado","900 EST","3,600"],
    ["The Reserve Jr. Suite Swim-Up","48","2 ad.","Acceso directo a alberca, jardín con cama balinesa","1,050 EST","4,200"],
    ["The Reserve Suite Ocean View","48","2 ad.","Vista mar, regadera de lluvia","1,080 EST","4,320"],
    ["The Reserve Grand Suite Ocean Front","75","2 ad.","Terraza grande frente al mar","1,400 EST","5,600"],
    ["The Reserve Presidential Ocean Front","155","4 ad.","2 recámaras, 3 baños, terraza con hot tub","2,400 EST","9,600"]]
},
{
 id:"melia-punta-cana", dest:"pc", tipo:"adultos", nombre:"Meliá Punta Cana Beach",
 cadena:"Meliá", zona:"Bávaro · Palma Real", ta:"4.4", taN:"12,019", taRank:"#15 de 56 en Bávaro",
 web:"https://www.melia.com/en/hotels/dominican-republic/punta-cana/melia-punta-cana-beach-resort",
 rooms:"https://www.melia.com/en/hotels/dominican-republic/punta-cana/melia-punta-cana-beach-resort/rooms",
 gal:"https://www.meliapuntacanabeach.com/accommodations.asp",
 datos:"465 habitaciones · renovado ~2019-20 · concepto wellness · ritual de aguas del spa incluido · swim-up bar sí",
 img:["https://dam.melia.com/melia/accounts/f8/4000018/projects/127/assets/76/71133/973ac8c619368eb62af7c0d7251daa83-1639125052.jpg",
      "https://www.meliapuntacanabeach.com/images/slides/slide-19.jpg",
      "https://dam.melia.com/melia/accounts/f8/4000018/projects/127/assets/0a/71132/50999a21ea50c184a71e3c1ca989e681-1639125052.jpg"],
 r:[["Deluxe Room (vista jardín)","42","2","Balcón, cafetera, minibar, amenities orgánicos","600 EST","2,400"],
    ["Premium Tropical Palms","42","2","Terraza, vista jardín","640 EST","2,560"],
    ["Premium Beachside","42","2","Cerca de playa y alberca principal","680 EST","2,720"],
    ["The Level Suite Tropical Palms","42","2","Lounge y check-in privados, desayuno VIP, room service 24 h","760 EST","3,040"],
    ["The Level Ocean Suite","84","2","Balcón con vista al Caribe, recámara y salón","1,000 EST","4,000"]]
},
{
 id:"excellence-el-carmen", dest:"pc", tipo:"adultos", nombre:"Excellence El Carmen",
 cadena:"Excellence Collection", zona:"Uvero Alto", ta:"4.6", taN:"13,255", taRank:"#4 de 9 en Uvero Alto",
 web:"https://www.excellenceresorts.com/punta-cana/excellence-el-carmen/",
 rooms:"https://www.excellenceresorts.com/punta-cana/excellence-el-carmen/rooms/",
 gal:"https://www.excellenceresorts.com/punta-cana/excellence-el-carmen/gallery",
 datos:"492 suites (todo suites) · abierto 2017 · 23 albercas · swim-up bar sí · 20 categorías de habitación, la variedad más grande del estudio",
 img:["https://84c1b501fde61dba63bc-fa6d706bb129c036124b532437347c9f.ssl.cf1.rackcdn.com/u/_xec/_suites/junior-suites-in-dominican-republic.jpg",
      "https://76a7b323da8554ec22e0-d946e249d9a895ced1092e3c543d8d1e.ssl.cf1.rackcdn.com/u/_excellence-club/best-adults-only-all-inclusive-resort-in-dominican-republic.jpg",
      "https://76a7b323da8554ec22e0-d946e249d9a895ced1092e3c543d8d1e.ssl.cf1.rackcdn.com/u/_bodas/dominican-republic-destination-beach-wedding.jpg"],
 r:[["Junior Suite Garden or Pool View","74","2-3","Balcón amueblado, jacuzzi para dos, baño de mármol","940 EST","3,760"],
    ["Junior Suite Ocean View","74","2","Vista mar + jacuzzi para dos","1,020 EST","4,080"],
    ["Junior Swim-Up Suite","88","2","Alberca conectada, terraza con lounge bed y spa jet","1,120 EST","4,480"],
    ["Terrace Suite with Plunge Pool","88","2","Terraza con plunge pool","1,200 EST","4,800"],
    ["XC Junior Swim-Up Suite","88","2","Excellence Club + swim-up","1,320 EST","5,280"],
    ["XC Beachfront Honeymoon Swim-Up","93","2","Club + swim-up frente a la playa","1,620 EST","6,480"],
    ["XC Two-Story Rooftop + Plunge Pool","149","2","2 pisos con rooftop y plunge pool","1,700 EST","6,800"]]
},
{
 id:"breathless-pc", dest:"pc", tipo:"adultos", nombre:"Breathless Punta Cana",
 cadena:"Hyatt Inclusive Collection", zona:"Uvero Alto", ta:"4.5", taN:"22,120", taRank:"#37 de 170 en Punta Cana",
 badge:"Fiesta", badgeCls:"ok",
 web:"https://www.hyattinclusivecollection.com/en/resorts-hotels/breathless/dominican-republic/punta-cana-resort-spa/",
 rooms:"https://www.hyattinclusivecollection.com/en/resorts-hotels/breathless/dominican-republic/punta-cana-resort-spa/accommodations/rooms-suites/",
 gal:"https://www.hyattinclusivecollection.com/en/resorts-hotels/breathless/dominican-republic/punta-cana-resort-spa/gallery/",
 datos:"750 suites · todas con hot tub en terraza · 4 albercas + lazy river · swim-up bar sí · el mejor entretenimiento de RD",
 img:["https://alg.widen.net/content/omjxikguiw/webp/BREPC-Allure-JR-TV-KING-CPC.webp?u=itfpsm&download=true&q=80",
      "https://alg.widen.net/content/cktvuu9mzj/webp/BREPC-EXT-FreestylePool-2-CB.webp?u=itfpsm&download=true&q=80",
      "https://alg.widen.net/content/vpwjfhfle0/webp/BREPC-EXT-Aerial-MainBeach-01-CPC.webp?u=itfpsm&download=true&q=80"],
 r:[["Allure Junior Suite Tropical View","51","3","Terraza privada con hot tub, doble lavabo","364 OF → 730 EST","2,920"],
    ["Allure Junior Suite Pool View","51","3","Vista alberca + hot tub","382 OF → 765 EST","3,060"],
    ["Allure Junior Suite Swim Up","51","3","Acceso swim-out + hot tub","416 OF → 832 EST","3,330"],
    ["xhale Club Jr. Suite Tropical View","56","3","Club: lounge, alberca y playa exclusivas","451 OF → 902 EST","3,610"],
    ["xhale Club Jr. Suite Swim Up","56","3","Club + swim-out + hot tub","537 OF → 1,074 EST","4,300"],
    ["xhale Club Master Suite Ocean Front","120","3","Frente al mar, terraza con camastros y hot tub","763 OF → 1,526 EST","6,100"]]
},
{
 id:"secrets-cap-cana", dest:"pc", tipo:"adultos", nombre:"Secrets Cap Cana",
 cadena:"Hyatt Inclusive Collection", zona:"Cap Cana · Playa Juanillo", ta:"4.8", taN:"25,939", taRank:"#2 de 11 en Cap Cana",
 badge:"Mejor playa", badgeCls:"ok",
 web:"https://www.hyattinclusivecollection.com/en/resorts-hotels/secrets/dominican-republic/cap-cana-resort-spa/",
 rooms:"https://www.hyattinclusivecollection.com/en/resorts-hotels/secrets/dominican-republic/cap-cana-resort-spa/accommodations/rooms-suites/",
 gal:"https://www.hyattinclusivecollection.com/en/resorts-hotels/secrets/dominican-republic/cap-cana-resort-spa/gallery/",
 datos:"457 suites · abierto 2016 · 20 categorías incluidas suites tipo bungalow · swim-up bar sí · 15 min del aeropuerto",
 alerta:"Las albercas NO están climatizadas y hay quejas documentadas de agua fría en enero.",
 img:["https://alg.widen.net/content/x8umxn23zv/webp/SECCC-JR-Night-4A-CB.webp?u=itfpsm&download=true&q=80",
      "https://alg.widen.net/content/jqfvs4u1vw/webp/SECCC-EXT-Main-Pool-2A.webp?u=itfpsm&download=true&q=80",
      "https://alg.widen.net/content/rfqlmmkph7/webp/SECCC-Couple-Beach-2B-CB.webp?u=itfpsm&download=true&q=80"],
 r:[["Junior Suite King","55","2","Baño con 2 regaderas de lluvia, balcón con tina de remojo","568 OF → 1,080 EST","4,320"],
    ["Junior Suite Ocean View","55","3","Vista mar","653 OF → 1,240 EST","4,960"],
    ["Junior Suite Swim Out","55","3","Swim-out directo desde la terraza","681 OF → 1,294 EST","5,180"],
    ["Preferred Club Jr. Suite Swim Out","55","2","Preferred + swim-out","824 OF → 1,566 EST","6,260"],
    ["PC Bungalow Suite Swim Out Ocean Front","72","2","Bungalow frente al mar con swim-out","1,107 OF → 2,103 EST","8,410"],
    ["PC Master Suite Ocean Front","118","2","Sala y comedor, balcón con tina","1,420 OF → 2,698 EST","10,790"]]
},
{
 id:"zilara-cap-cana", dest:"pc", tipo:"adultos", nombre:"Hyatt Zilara Cap Cana",
 cadena:"Playa Hotels / Hyatt", zona:"Cap Cana · Playa Juanillo", ta:"4.9", taN:"9,506", taRank:"#1 de 11 en Cap Cana",
 badge:"Mejor nota del país", badgeCls:"best",
 web:"https://www.hyatt.com/en-US/hotel/dominican-republic/hyatt-zilara-cap-cana/pujia",
 rooms:"https://www.resortsbyhyatt.com/zilara/zilara-cap-cana/adult-only-all-inclusive-resort-suites",
 gal:"https://www.hyatt.com/en-US/hotel/dominican-republic/hyatt-zilara-cap-cana/pujia/gallery",
 datos:"375 suites frente al mar · abierto nov 2019 · 12 restaurantes y 13 bares + acceso al Ziva contiguo · World of Hyatt · 15 min del aeropuerto",
 alerta:"Albercas sin climatizar: reseñas de enero-febrero reportan agua fría.",
 img:["https://playa-cms-assets.s3.amazonaws.com/media/Hyatt_Zilara_Cap_Cana/rooms/new20/hyatt-zilara-cap-cana-junior-suite-swim-up-king-room5.jpg",
      "https://playa-cms-assets.s3.amazonaws.com/media/Hyatt_Zilara_Cap_Cana/thingstodo/2024/hyatt-ziva-cap-cana-ocean-deck-5.jpg",
      "https://playa-cms-assets.s3.amazonaws.com/media/Hyatt_Zilara_Cap_Cana/rooms/new20/hyatt-zilara-cap-cana-ocean-view-one-bedroom-master-swim-up-suite-room.jpg"],
 r:[["Junior Suite King / Double","56","2-4","Balcón amueblado, cama Hyatt Grand, TV 55\"","1,080 EST","4,320"],
    ["Ocean View Junior Suite","56","2-4","Balcón con vista al mar","1,220 EST","4,880"],
    ["Club Ocean View Junior Suite","56","2-4","Club: concierge, lounge, alberca privada, licores premium","1,380 EST","5,520"],
    ["Club Junior Suite Swim Up","56","2-4","Club + alberca semiprivada desde la terraza","1,460 EST","5,840"],
    ["Club Ocean Front Jr. Suite Swim Up","56","2-4","Club + frente al mar + swim-up","1,640 EST","6,560"],
    ["Club One Bedroom Master Suite","115","4","Sala, hot tub privado, mayordomo","1,900 EST","7,600"]]
},

/* ===================== PUNTA CANA · FAMILIAR ===================== */
{
 id:"majestic-elegance", dest:"pc", tipo:"familiar", nombre:"Majestic Elegance Punta Cana",
 cadena:"Majestic Resorts", zona:"Bávaro", ta:"4.6", taN:"29,921", taRank:"#3 de 56 en Bávaro",
 badge:"Mejor familiar", badgeCls:"best",
 web:"https://www.majestic-resorts.com/punta-cana/resorts/majestic-elegance-punta-cana",
 rooms:"https://www.majestic-resorts.com/punta-cana/resorts/majestic-elegance-punta-cana/rooms",
 gal:"https://www.majestic-resorts.com/punta-cana/resorts/majestic-elegance-punta-cana/gallery",
 datos:"9 albercas incluida una tipo río de 300 m · Splash Kids, club infantil y sala para adolescentes · zona familiar separada del club de adultos · golf, tenis y pickleball incluidos · 25-30 min del aeropuerto",
 img:["https://www.majestic-resorts.com/dam/jcr:cef1664c-00ff-462f-b12e-5830cfa54e70/junior-suite-jacuzzy-majestic-elegance-punta-cana.webp",
      "https://www.majestic-resorts.com/dam/jcr:cf53d504-fb77-4fb8-b19b-4f0061deb620/gallery10-majestic-elegance-punta-cana.jpg",
      "https://www.majestic-resorts.com/dam/jcr:8ae77283-98ae-4087-b412-16c1434ef326/gallery17-majestic-elegance-punta-cana.jpg"],
 r:[["Junior Suite con Jacuzzi","49","2 ad. + 2 niños","Jacuzzi interior, balcón, minibar diario, room service","700-820 EST","2,800-3,280"],
    ["Colonial Junior Suite","49","2 ad. + 2 niños","Terraza con 2 camastros, jacuzzi exterior e interior, Nespresso","790-910 EST","3,160-3,640"],
    ["Majestic Junior Suite Swim Up","49","2 ad. + 2 niños","Jardín con camastros y acceso directo a alberca","850-980 EST","3,400-3,920"],
    ["One Bedroom Suite con Jacuzzi","99","2 ad. + 2 niños","Sala separada de la recámara — privacidad de los niños","1,000-1,150 EST","4,000-4,600"]]
},
{
 id:"dreams-onyx", dest:"pc", tipo:"familiar", nombre:"Dreams Onyx Resort & Spa",
 cadena:"Hyatt Inclusive Collection", zona:"Uvero Alto", ta:"4.6", taN:"13,637", taRank:"#7 en Punta Cana",
 badge:"Parque acuático", badgeCls:"ok",
 web:"https://www.hyattinclusivecollection.com/en/resorts-hotels/dreams/dominican-republic/onyx-resort-spa/",
 rooms:"https://www.hyattinclusivecollection.com/en/resorts-hotels/dreams/dominican-republic/onyx-resort-spa/accommodations/rooms-suites/",
 gal:"https://www.hyattinclusivecollection.com/en/resorts-hotels/dreams/dominican-republic/onyx-resort-spa/gallery/",
 datos:"Jungle Waterpark con 4 toboganes y río lento · Explorer's Club 3-12 con personal certificado por Cruz Roja · Core Zone Teens 13-17 · 6 albercas · intercambio con el Breathless contiguo · World of Hyatt",
 img:["https://alg.widen.net/content/gp4r7jiutc/webp/DROPC-2BED-FAM-TC.webp?u=itfpsm&download=true&q=80",
      "https://alg.widen.net/content/866useruea/webp/DROPC-EXT-Jungle-Water-Park-TC.webp?u=itfpsm&download=true&q=80",
      "https://alg.widen.net/content/gnqtv0qsb7/webp/DROPC-EXT-Family-Beach1-2A-CB.webp?u=itfpsm&download=true&q=80"],
 r:[["Junior Suite Garden View","56","4 (2 ad. + 2 niños)","Unlimited-Luxury, room service 24 h, licores premium","154 OF pp → 680-800 EST","2,720-3,200"],
    ["Premium Junior Suite Pool View","60","5","Vista alberca","168 OF pp → 760-880 EST","3,040-3,520"],
    ["Junior Suite Swim-Up","56","4","Acceso directo a alberca","183 OF pp → 820-950 EST","3,280-3,800"],
    ["Two Bedroom Family Suite","180","10 (5 ad. + 5 niños)","2 recámaras dentro de la zona del Jungle Waterpark","1,900-2,300 EST","7,600-9,200"]]
},
{
 id:"ocean-el-faro", dest:"pc", tipo:"familiar", nombre:"Ocean El Faro",
 cadena:"Ocean Hotels (H10)", zona:"Uvero Alto", ta:"4.3", taN:"10,056", taRank:"#5 de 9 en Uvero Alto",
 badge:"Más barato", badgeCls:"ok",
 web:"https://www.oceanhotels.com/en/punta-cana-hotels/ocean-el-faro",
 rooms:"https://www.oceanhotels.com/en/punta-cana-hotels/ocean-el-faro/rooms",
 gal:"https://www.oceanhotels.com/en/punta-cana-hotels/ocean-el-faro/gallery",
 datos:"Parque acuático con 4 toboganes y río lento · boliche de 6 líneas · minigolf · 8 canchas de tenis · Daisy Club y Teen Club · zona 18+ separada (El Beso)",
 alerta:"Reseñas 2025-26 reportan olor a humedad, aire acondicionado débil y refrigeradores descompuestos. Pedir habitación renovada por escrito.",
 img:["https://pro-static.h10hotels.com/gallery/T2D3/07_OEFJuniorSuitePoolView.jpg",
      "https://pro-static.h10hotels.com/gallery/T1D3/12_OEBLazyRiver.jpg",
      "https://pro-static.h10hotels.com/gallery/T1D3/04_OEFAerialView.jpg"],
 r:[["Junior Suite Pool View","~45","2 ad. + 2 niños","Sala separada con sofá cama, terraza a la alberca","560-680 EST","2,240-2,720"],
    ["Junior Suite Waterpark Side","~45","2 ad. + 2 niños","Al lado del parque acuático — la mejor para niños chicos","600-720 EST","2,400-2,880"],
    ["Junior Suite Ocean View","~45","2 ad. + 2 niños","Terraza al mar","640-780 EST","2,560-3,120"]]
},
{
 id:"iberostar-bavaro", dest:"pc", tipo:"familiar", nombre:"Iberostar Selection Bávaro Suites",
 cadena:"Iberostar", zona:"Playa Bávaro", ta:"4.4", taN:"13,897", taRank:"Bávaro",
 web:"https://www.iberostar.com/en/hotels/punta-cana/iberostar-selection-bavaro-suites/",
 rooms:"https://www.iberostar.com/en/hotels/punta-cana/iberostar-selection-bavaro-suites/",
 gal:"https://www.iberostar.com/en/hotels/punta-cana/iberostar-selection-bavaro-suites/",
 datos:"Star Camp segmentado: Kangaroo 0-3, Monkey 4-6, Dolphin 7-12, Eagle 13-15 · Aquafun con barco pirata y toboganes · todo suites · sobre Playa Bávaro · 25-30 min del aeropuerto",
 img:["https://apiimg.iberostar.com/uploads/image/56218/crops/16:9/1920/image.jpeg"],
 r:[["Junior Suite Family","41","2 ad. + 2 niños","Cama king + literas, junto al Star Camp, sala, Chromecast","700-820 EST","2,800-3,280"],
    ["Junior Suite Pool Access","41","2 ad. + 2 niños","2 camas dobles, acceso a alberca","800-930 EST","3,200-3,720"],
    ["Junior Suite Beach Access","41","2 ad. + 2 niños","Acceso directo a la playa, mayordomo","880-1,020 EST","3,520-4,080"],
    ["Connecting Junior Suite Family","82","hasta 6","Dos recámaras y dos balcones, PlayStation disponible","1,150-1,350 EST","4,600-5,400"]]
},
{
 id:"hard-rock-pc", dest:"pc", tipo:"familiar", nombre:"Hard Rock Hotel & Casino Punta Cana",
 cadena:"Hard Rock", zona:"Playa Macao", ta:"4.3", taN:"42,983", taRank:"#31 de 56 en Bávaro",
 badge:"26 toboganes", badgeCls:"ok",
 web:"https://hotel.hardrock.com/punta-cana/",
 rooms:"https://hotel.hardrock.com/punta-cana/rooms-and-suites.aspx",
 gal:"https://hotel.hardrock.com/punta-cana/gallery.aspx",
 datos:"Rockaway Bay Water Park con 26 toboganes incluido · 13 albercas y 4 swim-up bars · Roxity Kids Club · 9 restaurantes · el casino más grande de RD · 1,882 habitaciones",
 alerta:"Reseñas 2025-26 reportan saturación: esperas de más de una hora en restaurantes y room service de hasta 2 horas.",
 img:["https://hotel.hardrock.com/punta-cana/files/6136/hard-rock-punta-cana-rock-family-suite-king-bed.jpg",
      "https://hotel.hardrock.com/punta-cana/files/6136/rockaway-bay-water-park-punta-cana-high-speed-slides.jpg",
      "https://hotel.hardrock.com/punta-cana/files/6136/beach-hard-rock-hotel-punta-cana.jpeg"],
 r:[["Caribbean Suite","73","3 ad. + 1 niño","King o 2 dobles + sofá cama, 9 restaurantes incluidos","1,050-1,250 EST","4,200-5,000"],
    ["Islander Junior Suite","76","3 ad. + 1 niño","King o 2 kings + sofá cama","1,150-1,350 EST","4,600-5,400"],
    ["Rock Family Suite (1 recámara)","159","6 (máx. 3 adultos)","King + dos sofás cama queen","1,600-1,900 EST","6,400-7,600"],
    ["Rock Suite (2 recámaras)","232","6","Tres camas king + dos sofás, asistente personal","2,100-2,500 EST","8,400-10,000"]]
},
{
 id:"nickelodeon-pc", dest:"pc", tipo:"familiar", nombre:"Nickelodeon Hotels & Resorts Punta Cana",
 cadena:"Karisma", zona:"Uvero Alto", ta:"4.3", taN:"7,999", taRank:"#6 de 10 en Uvero Alto",
 web:"https://www.karismahotels.com/nickelodeon-hotels-resorts/punta-cana",
 rooms:"https://www.karismahotels.com/nickelodeon-hotels-resorts/punta-cana",
 gal:"https://www.nickresorts.com/",
 datos:"Aqua Nick, parque acuático temático · Character Central con personajes de Nickelodeon · experiencias de slime · club infantil y niñera · 460 suites",
 alerta:"Reseñas 2025-26 duras: moho, esperas de hasta 2 horas en check-in y room service, costos ocultos por cenar con personajes y presión de tiempo compartido. Es el de peor relación precio/ejecución.",
 img:[],
 r:[["Pool Side Mates Suite","~65","2 ad. + 2 niños","Gourmet Inclusive de Karisma, suite de dos ambientes","1,100-1,350 EST","4,400-5,400"],
    ["Swim-Up Mates Suite","~65","2 ad. + 2 niños","Acceso directo a alberca","1,400-1,700 EST","5,600-6,800"],
    ["Pineapple Villa / Super Villa","150-350","6-12","Villas temáticas con alberca privada","2,800-4,500 EST","11,200-18,000"]]
},

/* ===================== CARIBE MEXICANO · SOLO ADULTOS ===================== */
{
 id:"royalton-chic", dest:"mx", tipo:"adultos", nombre:"Royalton CHIC Cancún",
 cadena:"Marriott Autograph Collection", zona:"Cancún ZH · Km 9.7", ta:"4.5", taN:"10,008", taRank:"Zona Hotelera",
 badge:"Mejor global", badgeCls:"best",
 web:"https://www.royaltonresorts.com/resorts/chic-cancun-resort-spa",
 rooms:"https://www.royaltonresorts.com/resorts/chic-cancun-resort-spa/suites",
 gal:"https://www.royaltonresorts.com/resorts/chic-cancun-resort-spa/gallery",
 datos:"458 suites · abierto 2019 · alberca rooftop Level 18 · swim-up bar sí · suma puntos Marriott Bonvoy · Coco Bongo y Punta Cancún a 700 m a pie",
 img:["https://marriott.cdn.tambourine.com/royalton-resorts/media/royalton_suites_cancun_luxury_junior_suite-8-624ef805e31c2.jpg",
      "https://marriott.cdn.tambourine.com/royalton-resorts/media/royalton_suites_cancun-12-62548527b327f-optimized.jpg",
      "https://marriott.cdn.tambourine.com/royalton-resorts/media/royalton_suites_cancun-2-625484f42265f-optimized.jpg"],
 r:[["Luxury Junior Suite","56","4 ad.","Balcón privado, vista mar o laguna, DreamBed","700-780 EST","2,800-3,120"],
    ["Luxury Suite","67","3 ad.","Balcón, vista oceanfront o sunset, sofá cama","760-850 EST","3,040-3,400"],
    ["Diamond Club Luxury Junior Suite","56","4 ad.","Mayordomo, lounge y playa exclusivos, check-in privado","820-950 EST","3,280-3,800"],
    ["DC Luxury Presidential 1 recámara","114","3 ad.","Jacuzzi en suite, bar en suite, mayordomo","1,300-1,600 EST","5,200-6,400"],
    ["DC Chairman's 2 recámaras","303","7 ad.","Mesa de billar, jacuzzi exterior, vista panorámica","2,500+ EST","10,000+"]]
},
{
 id:"privilege-aluxes", dest:"mx", tipo:"adultos", nombre:"Privilege Aluxes Isla Mujeres",
 cadena:"Privilege Hotels", zona:"Isla Mujeres · Centro", ta:"4.5", taN:"5,133", taRank:"#2 de 53 en Isla Mujeres",
 badge:"Mejor precio + playa", badgeCls:"best",
 web:"https://www.privilegehotels.com/",
 rooms:"https://www.privilegehotels.com/rooms",
 gal:"https://www.privilegehotels.com/gallery",
 datos:"124 habitaciones · 2 albercas climatizadas y 3 jacuzzis · swim-up bar (Wet Bar) · a pie del malecón, la calle Hidalgo, el ferry y Playa Norte (la mejor playa nadable del estudio)",
 img:["https://www.privilegehotels.com/images/custom/rooms/ocean-deluxe-suite/ocean-deluxe-suite-00.jpg",
      "https://www.privilegehotels.com/images/custom/galeria/hotel/galeria_hotel_1_mini.jpg",
      "https://www.privilegehotels.com/images/custom/rooms/wow-privilege/wow-privilege-00.jpg"],
 r:[["Aluxes Room","n/d","2","King, regadera y tina, balcón vista jardín","330-400 EST","1,320-1,600"],
    ["Superior Aluxes","n/d","2","King, jacuzzi en el balcón","380-450 EST","1,520-1,800"],
    ["Deluxe Suite Ocean View","n/d","3","Sala independiente, balcón privado, tina de hidromasaje, vista mar","470-560 EST","1,880-2,240"],
    ["Premium Suite","n/d","3","Sala, jacuzzi en el balcón","520-620 EST","2,080-2,480"],
    ["Wow Privilege","n/d","2","Alberca privada en rooftop, cama balinesa","650-800 EST","2,600-3,200"],
    ["Grand Platinum Suite","n/d","2-3","Dos niveles, alberca privada rooftop, vista Caribe","800-1,000 EST","3,200-4,000"]]
},
{
 id:"royal-hideaway", dest:"mx", tipo:"adultos", nombre:"Royal Hideaway Playacar",
 cadena:"Barceló", zona:"Playacar, Playa del Carmen", ta:"4.5", taN:"10,464", taRank:"Playa del Carmen",
 badge:"Precio real más bajo", badgeCls:"ok",
 web:"https://www.barcelo.com/en-us/royal-hideaway-playacar/",
 rooms:"https://www.barcelo.com/en-us/royal-hideaway-playacar/rooms/",
 gal:"https://www.barcelo.com/en-us/royal-hideaway-playacar/galleries/",
 datos:"201 habitaciones · 6 albercas (4 de relajación + 1 infinity con cascada) · AAA 4 Diamantes · SIN swim-up bar · la Quinta Avenida a 5 min en taxi",
 alerta:"No tiene swim-up bar ni coffee bar, y las habitaciones piden renovación. Público 40+ tranquilo: es descanso, no fiesta.",
 img:[],
 r:[["Luxury","50","3 ad.","Bata, hidromasaje, terraza","187 OF → 390-460 EST","1,560-1,840"],
    ["Luxury Royal View","50","3 ad.","Balcón o terraza, minibar, vista jardines","199 OF → 410-490 EST","1,640-1,960"],
    ["Luxury Relax Pool","50","3 ad.","Junto a alberca de relajación, hidromasaje","205 OF → 430-510 EST","1,720-2,040"],
    ["Honeymoon Suite","124","2 ad.","Hidromasaje, sala","248 OF → 520-620 EST","2,080-2,480"],
    ["Suite Ocean View","124","2 ad.","Hidromasaje, vista mar","278 OF → 580-690 EST","2,320-2,760"],
    ["Royal Casita","215","5 ad.","Casita independiente","961 OF → 1,700-2,000 EST","6,800-8,000"]]
},
{
 id:"hyatt-vivid-pdc", dest:"mx", tipo:"adultos", nombre:"Hyatt Vivid Playa del Carmen",
 cadena:"Hyatt Inclusive Collection", zona:"Centro de Playa del Carmen", ta:"4.6", taN:"24,291", taRank:"Playa del Carmen",
 badge:"Cero concesiones", badgeCls:"best",
 web:"https://www.hyattinclusivecollection.com/en/resorts-hotels/hyatt-vivid/mexico/playa-del-carmen/",
 rooms:"https://www.hyattinclusivecollection.com/en/resorts-hotels/hyatt-vivid/mexico/playa-del-carmen/accommodations/rooms-suites/",
 gal:"https://www.resortsbyhyatt.com/Vivid/Vivid-playa-del-carmen",
 datos:"524 suites · playa propia + la Quinta Avenida a 400 m caminando · 13 restaurantes y bares · swim-up bar sí · alberca olímpica y cancha de tenis en azotea",
 img:["https://alg.widen.net/content/i4ilnin1em/webp/HVPDC-P0005-Junior-Suite-Swim-Up-King-Bed.webp",
      "https://alg.widen.net/content/qkd4mjcjnr/webp/HVPDC-P0007-Junior-Suite-Ocean-Front-Walk-Out-King.webp"],
 r:[["Junior Suite","61","4","Balcón amueblado, tina doble de hidromasaje, doble lavabo","430-520 EST","1,720-2,080"],
    ["Junior Suite Garden View","61","4","Balcón, tina doble jets, vista jardín","450-540 EST","1,800-2,160"],
    ["Junior Suite Swim-Up","61","2","Terraza con acceso directo a alberca semiprivada","560-670 EST","2,240-2,680"],
    ["Junior Suite Oceanfront Walk-Out","61","2","Terraza con acceso a la playa, tina doble jets","610-730 EST","2,440-2,920"],
    ["One Bedroom Suite King","124","2","Sala y comedor, cabaña de playa asignada","780-950 EST","3,120-3,800"],
    ["Presidential Suite King","182","2","Terraza rooftop privada con alberca y bar","1,500-1,900 EST","6,000-7,600"]]
},
{
 id:"excellence-rc", dest:"mx", tipo:"adultos", nombre:"Excellence Riviera Cancún",
 cadena:"Excellence Collection", zona:"Puerto Morelos", ta:"4.7", taN:"27,638", taRank:"#1 de 44 en Puerto Morelos",
 badge:"Mejor reputación", badgeCls:"best",
 web:"https://www.excellenceresorts.com/riviera-maya-cancun/excellence-riviera-cancun/",
 rooms:"https://www.excellenceresorts.com/riviera-maya-cancun/excellence-riviera-cancun/rooms/",
 gal:"https://www.excellenceresorts.com/riviera-maya-cancun/excellence-riviera-cancun/gallery/",
 datos:"~440 suites · 6 albercas y lazy river · 8 restaurantes sin reserva y 10 bares · swim-up bar sí · a 25 min del aeropuerto",
 img:["https://84c1b501fde61dba63bc-fa6d706bb129c036124b532437347c9f.ssl.cf1.rackcdn.com/responsive/4:3/750px/u/_xrc/_suites/luxury-jacuzzi-junior-suite-excellence-riviera-cancun.jpg",
      "https://1f4ce3cae3f3395d5ce0-69065588188907c78332bfb3d08ee9ab.ssl.cf1.rackcdn.com/responsive/Native/750px/u/_destination/best-deals-all-inclusive-resorts-riviera-maya-pool.jpg",
      "https://1f4ce3cae3f3395d5ce0-69065588188907c78332bfb3d08ee9ab.ssl.cf1.rackcdn.com/responsive/Native/750px/u/_resort/excellence-riviera-cancun-beach-all-inclusive-resort.jpg"],
 r:[["Junior Suite Spa or Pool View","62","3","Jacuzzi en suite, terraza, mármol, Nespresso, TV 55\"","620-850 OF (20 dic-5 ene)","2,480-3,400"],
    ["Junior Swim-Up Suite","62","3","Acceso directo a alberca desde la terraza","700-930 EST","2,800-3,720"],
    ["Junior Suite Ocean View","62","2","Vista mar, balcón, jacuzzi","700-920 EST","2,800-3,680"],
    ["Two-Story Rooftop Terrace Suite","98","2","Dos niveles + rooftop con plunge pool climatizado","850-1,100 EST","3,400-4,400"],
    ["EC Junior Suite Ocean Front","62","2","Excellence Club + plunge pool privado, acceso a playa","850-1,120 EST","3,400-4,480"],
    ["EC Honeymoon Suite Ocean Front","97","2","Club, dos balcones, sala separada, frente al mar","1,000-1,300 EST","4,000-5,200"]]
},
{
 id:"margaritaville", dest:"mx", tipo:"adultos", nombre:"Margaritaville Island Reserve Riviera Maya",
 cadena:"Karisma", zona:"Puerto Morelos", ta:"4.6", taN:"2,489", taRank:"#12 de 44 en Puerto Morelos",
 web:"https://www.karismahotels.com/margaritaville/margaritaville-island-reserve-riviera-maya",
 rooms:"https://www.karismahotels.com/margaritaville/margaritaville-island-reserve-riviera-maya/accommodations",
 gal:"https://www.karismahotels.com/margaritaville/margaritaville-island-reserve-riviera-maya/gallery",
 datos:"355 suites · abierto 2023 · 3 albercas y DOS swim-up bars · única cervecería LandShark de México · a 25 min del aeropuerto",
 img:["https://admin.karismahotels.com/sites/default/files/styles/card_image_desktop/public/2024-04/Oceanfront%20Chillout%20Suite%20Rooms%20Margaritaville%20Riviera%20Maya%203.jpg",
      "https://admin.karismahotels.com/sites/default/files/styles/wide/public/2024-06/5%20O%C2%B4Clock%20Somewhere%20Bar%20Restaurants%20And%20Bars%20Margaritaville%20Riviera%20Maya%202.jpg",
      "https://admin.karismahotels.com/sites/default/files/styles/card_image_desktop/public/2025-03/Oceanfront%20Infinity%20Pool%20Suite%20Rooms%20Margaritaville%20Riviera%20Maya%202.jpg"],
 r:[["Island Oasis Suite","42","2 ad.","Planta baja, vista jardín, hamaca, terraza, sala","450-540 EST","1,800-2,160"],
    ["Queen Paradise Room","42","3 ad.","2 queen, pisos 2-4, comedor, terraza amueblada","470-560 EST","1,880-2,240"],
    ["Oceanfront Chillout Suite","44","2 ad.","Piso 5, vista mar, tina exenta, regadera de lluvia","580-700 EST","2,320-2,800"],
    ["Oceanfront Infinity Pool Suite","43","2 ad.","Acceso directo a alberca infinity, tina exenta","650-790 EST","2,600-3,160"],
    ["Oceanfront Honeymoon Suite","63","2 ad.","Frente al mar, doble lavabo, doble regadera de lluvia","800-970 EST","3,200-3,880"]]
},
{
 id:"riu-las-americas", dest:"mx", tipo:"adultos", nombre:"Riu Palace Las Américas",
 cadena:"RIU", zona:"Cancún ZH · Km 8.5", ta:"4.5", taN:"5,543", taRank:"Zona Hotelera",
 badge:"El más céntrico", badgeCls:"ok",
 web:"https://www.riu.com/en/hotel/mexico/cancun/hotel-riu-palace-las-americas",
 rooms:"https://www.riu.com/en/hotel/mexico/cancun/hotel-riu-palace-las-americas/rooms/",
 gal:"https://www.riu.com/en/hotel/mexico/cancun/hotel-riu-palace-las-americas",
 datos:"372 suites · swim-up bar sí · brazalete de intercambio con Riu Cancún y Riu Caribe (~18 restaurantes) · Coco Bongo y Forum by the Sea caminando",
 img:["https://www.riu.com/dam/Ficha-Hotel/Hotel-Riu-Palace-Las-Americas/Habitaciones/rooms-hotel-riu-palace-las-americas-SUMZ.jpg",
      "https://www.riu.com/dam/Ficha-Hotel/Hotel-Riu-Palace-Las-Americas/Piscinas/pool-hotel-riu-palace-las-americas.jpg",
      "https://www.riu.com/dam/Ficha-Hotel/Hotel-Riu-Palace-Las-Americas/Playa/beach-hotel-riu-palace-las-americas.jpg"],
 r:[["Jr. Suite","35","2-3","Regadera, bata, dispensador de licores en habitación","164 OF → 400-450 EST","1,600-1,800"],
    ["Jr. Suite con Vista al Mar","35","2-3","Vista mar o lateral","180 OF → 440-500 EST","1,760-2,000"],
    ["Suite con Vista al Mar","70","2-4","Suite amplia, bata, ventilador de techo","206 OF → 500-570 EST","2,000-2,280"],
    ["Suite Jacuzzi con Vista al Mar","61","2-4","Jacuzzi, vista mar","228 OF → 560-640 EST","2,240-2,560"]]
},
{
 id:"riu-kukulkan", dest:"mx", tipo:"adultos", nombre:"Riu Palace Kukulkán",
 cadena:"RIU", zona:"Cancún ZH · Km 12", ta:"4.5", taN:"1,704", taRank:"Zona Hotelera",
 badge:"Nuevo + barato", badgeCls:"ok",
 web:"https://www.riu.com/en/hotel/mexico/cancun/hotel-riu-palace-kukulkan",
 rooms:"https://www.riu.com/en/hotel/mexico/cancun/hotel-riu-palace-kukulkan/rooms/",
 gal:"https://www.riu.com/en/hotel/mexico/cancun/hotel-riu-palace-kukulkan",
 datos:"426 habitaciones · inaugurado en noviembre de 2022, sin desgaste · 4 albercas · swim-up bar sí · 7 restaurantes y 5 bares · frente a La Isla Shopping Village",
 img:["https://www.riu.com/dam/Ficha-Hotel/Hotel-Riu-Palace-Kukulkan/Habitaciones/room-hotel-riu-palace-kukulkan-SUME.jpg",
      "https://www.riu.com/dam/Ficha-Hotel/Hotel-Riu-Palace-Kukulkan/Piscinas/pool-hotel-riu-palace-kukulkan-2.jpg",
      "https://www.riu.com/dam/Ficha-Hotel/Hotel-Riu-Palace-Kukulkan/elite-club/beach-elite-club-hotel-riu-palace-kukulkan.jpg"],
 r:[["Jr. Suite Vista Jardín","40","2-3","Balcón o terraza, tina y regadera, bata","156 OF → 420-480 EST","1,680-1,920"],
    ["Jr. Suite Vista Parcial al Mar","40","2-3","Vista lateral al mar","166 OF → 440-510 EST","1,760-2,040"],
    ["Jr. Suite Vista al Mar","40","2-3","Sofá cama, balcón o terraza","172 OF → 460-530 EST","1,840-2,120"],
    ["Jr. Suite Ocean View · Elite Club","40","2-3","Elite Club: playa y desayuno exclusivos, reservas prioritarias","191 OF → 510-590 EST","2,040-2,360"],
    ["Jr. Suite Ocean Front · Elite Club","40","2-3","Elite Club, frente al mar","207 OF → 550-640 EST","2,200-2,560"],
    ["Suite Ocean View · Elite Club","60","2-4","Elite Club, suite amplia con vista mar","246 OF → 660-760 EST","2,640-3,040"]]
},
{
 id:"secrets-the-vine", dest:"mx", tipo:"adultos", nombre:"Secrets The Vine Cancún",
 cadena:"Hyatt Inclusive Collection", zona:"Cancún ZH · Km 14.5", ta:"4.6", taN:"19,500", taRank:"#20 de 46 todo incluido de Cancún",
 web:"https://www.hyattinclusivecollection.com/en/resorts-hotels/secrets/mexico/the-vine-cancun/",
 rooms:"https://www.hyattinclusivecollection.com/en/resorts-hotels/secrets/mexico/the-vine-cancun/accommodations/rooms-suites/",
 gal:"https://www.hyattinclusivecollection.com/en/resorts-hotels/secrets/mexico/the-vine-cancun/gallery/",
 datos:"497 habitaciones, todas con vista al mar · muro de vinos de 3,000 etiquetas con sommelier · swim-up bar sí (sin habitaciones swim-up) · fine dining externo en la misma cuadra",
 img:["https://alg.widen.net/content/7swz95jyfl/webp/SEVCU-DLX-OV-1A-CB.webp",
      "https://alg.widen.net/content/qaipbrcrpb/webp/SEVCU-EXT-InfinityPool-Couple-3-CB.webp",
      "https://alg.widen.net/content/cx0yfoltsi/webp/SEVCU-EXT-CoupleBeach1-2-CB.webp"],
 r:[["Deluxe Partial Ocean View","44","3","Porcelanato italiano, baño de cristal, balcón de teca","393 OF → 500-620 EST","2,000-2,480"],
    ["Deluxe Ocean View","44","3","Vista mar plena","405 OF → 520-640 EST","2,080-2,560"],
    ["Junior Suite Ocean View","66","2","King, balcón de teca, vista mar","420 OF → 550-670 EST","2,200-2,680"],
    ["Honeymoon Suite Ocean View","72","2","Tina de inmersión en la habitación","467 OF → 600-740 EST","2,400-2,960"],
    ["Master Suite Ocean View","123","3","Sala, comedor, tina de inmersión, balcón esquinero","486 OF → 640-790 EST","2,560-3,160"],
    ["Master Suite Ocean Front","123","3","Frente al mar, opción Preferred Club","603 OF → 780-950 EST","3,120-3,800"]]
},
{
 id:"zilara-cancun", dest:"mx", tipo:"adultos", nombre:"Hyatt Zilara Cancún",
 cadena:"Playa Hotels / Hyatt", zona:"Cancún ZH · Km 11.5", ta:"4.7", taN:"14,845", taRank:"#10 de 253 en Cancún",
 badge:"Renovado 2026", badgeCls:"new",
 web:"https://www.hyatt.com/zilara/en-US/cunia-hyatt-zilara-cancun",
 rooms:"https://www.hyatt.com/zilara/en-US/cunia-hyatt-zilara-cancun/rooms",
 gal:"https://www.resortsbyhyatt.com/zilara/zilara-cancun",
 datos:"310 suites · reapertura mayo 2026 tras renovación integral de un año · 12 restaurantes reimaginados (Bokeh, Casa Adelita, Olio D'Olivia) · Zen Spa nuevo · swim-up bar y suites swim-up · World of Hyatt",
 alerta:"No comparte instalaciones con el Hyatt Ziva vecino: son hoteles separados (error común al reservar).",
 img:[],
 r:[["Junior Suite (King o 2 dobles)","60","2-4","Tina doble de hidromasaje, terraza privada, Nespresso","600-750 EST","2,400-3,000"],
    ["Ocean View Junior Suite","60","2-4","Balcón con hamaca, vista Caribe","385 OF → 680-850 EST","2,720-3,400"],
    ["Oceanfront Junior Suite","60","2-4","Vista frontal sin obstrucción, doble lavabo","750-930 EST","3,000-3,720"],
    ["Oceanfront Luxury Suite","70","2","Terraza envolvente, acceso a spa","880-1,100 EST","3,520-4,400"],
    ["Oceanview Swim-Up Suite","79","2","Acceso directo a alberca semiprivada, split-level","950-1,200 EST","3,800-4,800"],
    ["Oceanfront Master Villa","108","2","Villa de dos niveles, jacuzzi exterior, mayordomo","1,300-1,650 EST","5,200-6,600"]]
},
{
 id:"live-aqua", dest:"mx", tipo:"adultos", nombre:"Live Aqua Beach Resort Cancún",
 cadena:"Posadas / La Colección", zona:"Cancún ZH · Km 12.5", ta:"4.7", taN:"18,668", taRank:"#5 de Cancún",
 web:"https://www.lacoleccionresorts.com/our-hotels/live-aqua-beach-resort-cancun",
 rooms:"https://www.aquabeachresortcancun.com/accommodations.asp",
 gal:"https://www.aquabeachresortcancun.com/accommodations.asp",
 datos:"371 habitaciones · 7 albercas incluidas infinity y de carriles, swim-up bar · aromaterapia en todo el hotel · buffet Siete considerado el mejor de la Zona Hotelera · La Isla enfrente",
 img:["https://www.aquabeachresortcancun.com/images/rooms/premium_room_ocean_front.jpg",
      "https://www.aquabeachresortcancun.com/images/all_inclusive.jpg",
      "https://www.aquabeachresortcancun.com/images/slides/slide-61.jpg"],
 r:[["Premium Garden View 1 King","33","2","Consola de iluminación inteligente, menú de aromaterapia","350 OF → 500-580 EST","2,000-2,320"],
    ["Premium Ocean View","33","2","Vista parcial al mar, balcón","420 OF → 600-700 EST","2,400-2,800"],
    ["Premium Ocean Front 1 King","33","2","Frente al mar directo","500 OF → 710-830 EST","2,840-3,320"],
    ["Premium Aqua Club Ocean Front","44","2","Aqua Club Exclusive Level, piso 5","600 OF → 850-1,000 EST","3,400-4,000"],
    ["Aqua Suite","60","3","Dos ambientes + jacuzzi de hidroterapia y cromoterapia","750 OF → 1,050-1,250 EST","4,200-5,000"]]
},
{
 id:"krystal-altitude", dest:"mx", tipo:"adultos", nombre:"Krystal Grand Cancún · nivel Altitude",
 cadena:"Krystal", zona:"Punta Cancún · Km 9.5", ta:"4.3", taN:"11,316", taRank:"#43 de 253 en Cancún",
 badge:"Centricidad máxima", badgeCls:"warn",
 web:"https://www.krystalgrand.com/",
 rooms:"https://en.krystalgrand-cancun.com/rooms/",
 gal:"https://www.krystalgrand.com/altitude_level.asp",
 datos:"395 habitaciones en total · Altitude ocupa una torre con lounge, bar privado, restaurante francés y alberca infinity solo adultos · playa con rompeolas (agua calmada) · Coco Bongo y Plaza Caracol caminando",
 alerta:"NO es un hotel solo adultos: el resort opera Kamp Krystal para niños de 3 a 10 años. Solo la alberca infinity y el restaurante Le Délice están restringidos a adultos. Precios publicados SIN impuestos (sumar ~19%).",
 img:["https://www.krystalgrand.com/images/gallery/gallery-1.jpg",
      "https://www.krystalgrand.com/images/all_inclusive.jpg",
      "https://www.krystalgrand.com/images/gallery/gallery-2.jpg"],
 r:[["Altitude Suite","51","2-3","Terraza privada, amenidades L'Occitane, minibar VIP con licores, cafetera, room service 24 h","431 OF + imp.","1,724 + imp."],
    ["Altitude Suite Ocean Front","51","2","Terraza privada, King, frente al mar, regadera de lluvia","443 OF + imp.","1,772 + imp."],
    ["Altitude Corner Suite Partial Ocean","n/d","2","Suite esquinera, solo King, terraza amueblada","509 OF + imp.","2,036 + imp."],
    ["Altitude Corner Suite Ocean Front","n/d","2","Pisos más altos, vista panorámica al mar","525 OF + imp.","2,100 + imp."],
    ["Altitude Master Suite","176","2-4","Vista panorámica, sala, jacuzzi en la terraza","1,193 OF + imp.","4,772 + imp."]]
},

/* ===================== CARIBE MEXICANO · FAMILIAR ===================== */
{
 id:"iberostar-paraiso", dest:"mx", tipo:"familiar", nombre:"Iberostar Selection Paraíso Maya Suites",
 cadena:"Iberostar", zona:"Playa Paraíso, Riviera Maya", ta:"4.4", taN:"8,827", taRank:"#6 de 11 en Playa Paraíso",
 badge:"Mejor familiar", badgeCls:"best",
 web:"https://www.iberostar.com/en/hotels/riviera-maya/iberostar-selection-paraiso-maya/",
 rooms:"https://www.iberostar.com/en/hotels/riviera-maya/iberostar-selection-paraiso-maya/",
 gal:"https://www.iberostar.com/en/hotels/riviera-maya/iberostar-selection-paraiso-maya/",
 datos:"7 toboganes, alberca de olas, río lento y alberca de chapoteo · Star Camp segmentado 0-3, 4-6, 7-12 y 13-15 · todo suites · intercambio con el complejo Paraíso · 30-35 min del aeropuerto",
 alerta:"Presión fuerte de tiempo compartido al llegar y camastros escasos en alberca y playa.",
 img:["https://apiimg.iberostar.com/uploads/image/85070/crops/16:9/1920/image.jpg"],
 r:[["Junior Suite","55","2 ad. + 2 niños","Todo suites, vista jardín o selva, king o 2 dobles, balcón","700-850 EST","2,800-3,400"],
    ["One Bedroom Family Near Pool","55","2 ad. + 2 niños","Sofá cama + litera, alberca semiprivada","750-900 EST","3,000-3,600"],
    ["One Bedroom Family Pool Walkout","55","2 ad. + 2 niños","Planta baja con acceso directo a alberca","820-980 EST","3,280-3,920"],
    ["Two Bedroom Family Junior Suite","110","hasta 6","Dos habitaciones comunicadas, dos balcones","1,200-1,450 EST","4,800-5,800"]]
},
{
 id:"gp-costa-mujeres", dest:"mx", tipo:"familiar", nombre:"Grand Palladium Select Costa Mujeres",
 cadena:"Palladium Hotel Group", zona:"Costa Mujeres", ta:"4.4", taN:"14,107", taRank:"Family Selection: 4.6 con 3,097",
 badge:"Mejor kids club", badgeCls:"ok",
 web:"https://www.palladiumhotelgroup.com/en/hotels/mexico/costamujerescancun/grand-palladium-select-costa-mujeres",
 rooms:"https://www.palladiumhotelgroup.com/en/hotels/mexico/costamujerescancun/grand-palladium-select-costa-mujeres/rooms",
 gal:"https://www.grandpalladiumcostamujeresresort.com/accommodations.asp",
 datos:"Baby Club 1-3 con cunas, Raggs Kids Club 4-12 y Black & White Club 13-17 abierto hasta medianoche — todos gratuitos · 670 suites con balcón e hidromasaje · Rafa Nadal Tennis Center · spa de 4,832 m² · playa con muy poco sargazo",
 alerta:"Hay obras de construcción reportadas en reseñas recientes. Confirmar por escrito que no habrá obras en diciembre.",
 img:["https://www.palladiumhotelgroup.com/content/dam/palladium/images/hoteles/mexico/costa-mujeres/habitaciones/grand-palladium-costa-mujeres-resort-spa/loft-suite-jacuzzi-terrace/LOFT-SUITE-GP-COSTA-MUJERES14.jpg",
      "https://www.palladiumhotelgroup.com/content/dam/palladium/images/hoteles/mexico/costa-mujeres/hotel/piscinas/grand-palladium-costa-mujeres-resort-spa/Grand-Palladium-Costa-Mujeres-Resort-Spa_Vista-general-de-la-piscina-principal.jpg",
      "https://www.palladiumhotelgroup.com/content/dam/palladium/images/hoteles/mexico/costa-mujeres/bodas/CMU_Weddings_3.jpg"],
 r:[["Junior Suite","66","3 + 1","Balcón o terraza con hidromasaje","780-950 EST","3,120-3,800"],
    ["Junior Suite Pool Access","66","3 + 1","Acceso directo a alberca","880-1,050 EST","3,520-4,200"],
    ["Family Selection Junior Suite","66","2 ad. + 2 niños","Mayordomo familiar, check-in privado, alberca y restaurante propios","950-1,150 EST","3,800-4,600"],
    ["Family Selection Loft Suite Jacuzzi","99","2 ad. + 2 niños","Dos niveles, jacuzzi en terraza","1,150-1,400 EST","4,600-5,600"],
    ["Signature Suite Swim Out Ocean View","123","4 ad. + 2 niños","Swim-out privado, vista mar","1,500-1,800 EST","6,000-7,200"],
    ["Residence Suite Panoramic Ocean View","136","6 ad. + 2 niños","La mejor para dos familias juntas","1,900-2,300 EST","7,600-9,200"]]
},
{
 id:"moon-palace", dest:"mx", tipo:"familiar", nombre:"Moon Palace Cancún",
 cadena:"Palace Resorts", zona:"Costa sur de Cancún", ta:"4.5", taN:"40,779", taRank:"#59 de 253 en Cancún",
 badge:"Niños gratis", badgeCls:"ok",
 web:"https://www.moonpalacecancun.com/",
 rooms:"https://www.moonpalacecancun.com/accommodations",
 gal:"https://thegrand.moonpalace.com/water-park",
 datos:"Promoción vigente: niños y adolescentes de 17 o menos se hospedan, juegan y comen gratis + USD 500 de crédito de resort reservando directo · The Playroom, FlyRider y club de teens Wired · la llegada más rápida del estudio (15-20 min del aeropuerto)",
 alerta:"El parque acuático está en Moon Palace The Grand, no en Moon Palace Cancún: confirmar por escrito que su sección tiene acceso, y que la promoción de niños gratis aplica a la semana del 31.",
 img:["https://media.moonpalacecancun.com/nizuc_pool_moon_palace_cancun_3fa4171ca3.webp",
      "https://media-thegrand.moonpalace.com/wave_pool_water_park_moon_palace_the_grand_cancun_cb1317a6b6_7cde2534bd.webp",
      "https://media-thegrand.moonpalace.com/splash_zone_water_park_moon_palace_the_grand_cancun_70a4c18399_2d1f32a246.webp"],
 r:[["Superior Deluxe Garden View","~60","hasta 5","Tina de hidromasaje doble, despachador de licores, minibar","900-1,050 EST","3,600-4,200"],
    ["Superior Deluxe Ocean View","~60","hasta 5","Con vista al mar","1,000-1,200 EST","4,000-4,800"],
    ["Swim Up Suite","~60","hasta 5","Acceso directo a alberca","1,100-1,300 EST","4,400-5,200"],
    ["Superior Family Deluxe","~120","7","Dos recámaras comunicadas, kit infantil, amenidades L'Oréal Kids","1,300-1,550 EST","5,200-6,200"],
    ["Superior Two Bedroom Presidential","~150","7","Dos recámaras, sala amplia","1,700-2,100 EST","6,800-8,400"]]
},
{
 id:"dreams-playa-mujeres", dest:"mx", tipo:"familiar", nombre:"Dreams Playa Mujeres Golf & Spa",
 cadena:"Hyatt Inclusive Collection", zona:"Playa Mujeres", ta:"4.4", taN:"9,322", taRank:"AAA Four Diamond",
 web:"https://www.hyattinclusivecollection.com/en/resorts-hotels/dreams/mexico/playa-mujeres-golf-spa-resort/",
 rooms:"https://www.hyattinclusivecollection.com/en/resorts-hotels/dreams/mexico/playa-mujeres-golf-spa-resort/accommodations/rooms-suites/",
 gal:"https://www.hyattinclusivecollection.com/en/resorts-hotels/dreams/mexico/playa-mujeres-golf-spa-resort/gallery/",
 datos:"502 suites · Explorer's Club y Core Zone para adolescentes con muro de escalada · parque acuático con toboganes y río lento · campo de golf · 25-30 min del aeropuerto · World of Hyatt",
 alerta:"Tiene delfinario en la propiedad y el traslado NO está incluido.",
 img:["https://alg.widen.net/content/pgn4jivkpq/webp/DREPM-EC-ExplorersClub-Outdoor-1A-CB.webp?u=itfpsm&download=true&q=80",
      "https://alg.widen.net/content/yd0qpvspln/webp/DREPM-EXT-Family-LazyRiver-2-CB.webp?u=itfpsm&download=true&q=80",
      "https://alg.widen.net/content/7iyhgmzpba/webp/DREPM-EXT-Family-Beach-1A-CB.webp?u=itfpsm&download=true&q=80"],
 r:[["Junior Suite Garden View","56","4 (máx. 3 adultos)","Unlimited-Luxury, sala separada, terraza con hot tub","224 OF pp → 950-1,150 EST","3,800-4,600"],
    ["Junior Suite Pool View","56","4","Vista alberca","229 OF pp → 980-1,180 EST","3,920-4,720"],
    ["Junior Suite Ocean View","56","4","Sala con sofá cama + terraza con hot tub","256 OF pp → 1,080-1,300 EST","4,320-5,200"],
    ["Family Junior Suite Garden View","112","8 (máx. 5 adultos)","Dos habitaciones comunicadas, dos salas, dos terrazas con hot tub","549 OF pp → 1,800-2,200 EST","7,200-8,800"]]
},
{
 id:"ziva-cancun", dest:"mx", tipo:"familiar", nombre:"Hyatt Ziva Cancún",
 cadena:"Playa Hotels / Hyatt", zona:"Punta Cancún", ta:"4.6", taN:"14,912", taRank:"#47 de 252 en Cancún",
 badge:"Mejor calificado", badgeCls:"ok",
 web:"https://www.resortsbyhyatt.com/ziva/ziva-cancun",
 rooms:"https://www.resortsbyhyatt.com/ziva/ziva-cancun/all-inclusive-family-resort-suites",
 gal:"https://www.hyatt.com/ziva/en-US/canif-hyatt-ziva-cancun",
 datos:"KidZ Club y Moods Teens Lounge · tres albercas infinity · DOS playas privadas con mar en tres lados (península de Punta Cancún) · el más céntrico de los familiares: La Isla y Coco Bongo cerca · World of Hyatt",
 alerta:"Las suites Swim-Up requieren 13+ y toda la torre Turquoize es 18+: no sirven para familia con niños chicos. Tiene delfinario.",
 img:[],
 r:[["Resort View King/Double","45","4","Sofá cama incluido","1,100-1,300 EST","4,400-5,200"],
    ["Ocean View / Oceanfront","45","4","Sofá cama, vista o frente al mar","1,250-1,500 EST","5,000-6,000"],
    ["Resort View Master","56","5","Sofá cama, más espacio","1,250-1,450 EST","5,000-5,800"],
    ["Oceanfront Pyramid Suite","122","5","Dos pisos, sofá cama","1,900-2,300 EST","7,600-9,200"],
    ["Club Two Bedroom Oceanfront","196","6","Dos recámaras","2,600-3,100 EST","10,400-12,400"]]
},
{
 id:"hotel-xcaret", dest:"mx", tipo:"familiar", nombre:"Hotel Xcaret México",
 cadena:"Grupo Xcaret", zona:"Playa del Carmen sur", ta:"4.6", taN:"16,082", taRank:"#51 de 309 en Playa del Carmen",
 badge:"8 parques incluidos", badgeCls:"ok",
 web:"https://www.hotelxcaret.com/en/hotel-xcaret-mexico/",
 rooms:"https://www.hotelxcaret.com/en/hotel-xcaret-mexico/all-inclusive-suites/",
 gal:"https://www.hotelxcaretmexico.com/en/all-fun-inclusive/",
 datos:"All-Fun Inclusive: acceso ilimitado a 8 parques (Xcaret, Xel-Há, Xplor, Xplor Fuego, Xoximilco, Xenses, Xenotes, Xailing) + shuttle cada 30 min + traslado redondo desde el aeropuerto + ferry a Isla Mujeres · AAA Five Diamond · 1,800 suites · ríos navegables",
 alerta:"El problema no es el producto sino la ejecución: esperas de 1-2 horas en room service y dificultad para conseguir reservación en restaurantes (queja repetida en 2025-26). Solo conviene si van a hacer 3 o más parques.",
 img:[],
 r:[["Junior Suite","55-65","2 ad. + 2 niños","All-Fun Inclusive: 8 parques + traslado + ferry","1,400-1,700 EST","5,600-6,800"],
    ["Swim Up Suite","55-65","2 ad. + 2 niños","Acceso directo a alberca o río","1,700-2,050 EST","6,800-8,200"],
    ["Family Master Suite","90-110","hasta 5","Espacios amplios, sala","2,200-2,700 EST","8,800-10,800"],
    ["Presidential Family Suite","130+","hasta 5","La categoría tope","3,000-3,800 EST","12,000-15,200"]]
}
];
